### ISSUE TITLE
2.9.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [pygments/pygments#1789] opened 2021-05-03 15:59 UTC
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pygments-2.9.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pygments-2.9.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/pygments-2.9.0, configfile: pytest.ini
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, asyncio-0.14.0, expect-1.1.0, cov-2.11.1, mock-3.5.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, flaky-3.7.0, cases-3.4.6, hypothesis-6.10.1, case-1.5.3, isort-1.3.0, aspectlib-1.5.2
collected 3713 items

[..]

================================================================================= FAILURES =================================================================================
________________________________________________________________________________ test_L_opt ________________________________________________________________________________

    def test_L_opt():
>       o = check_success('-L')

tests/test_cmdline.py:160:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmdline = ('-L',), kwds = {}, code = 1
out = 'Pygments version 2.9.0, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.\n\nFilters:\n~~~~~~~~\n* co...s version of the "gruvbox" dark vim theme.\n* gruvbox-light:\n    Pygments version of the "gruvbox" Light vim theme.\n'
err = '\n*** Error while highlighting:\nDeprecationWarning: \'environmentfilter\' is renamed to \'pass_environment\', the ol...s/jinja2/filters.py", line 88, in environmentfilter)\n*** If this is a bug you want to report, please rerun with -v.\n'
@py_assert2 = 0, @py_assert1 = False, @py_format4 = '1 == 0', @py_format6 = 'assert 1 == 0'

    def check_success(*cmdline, **kwds):
        code, out, err = run_cmdline(*cmdline, **kwds)
>       assert code == 0
E       assert 1 == 0

tests/test_cmdline.py:65: AssertionError
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/test_guess.py:24: This is identified as T-SQL
SKIPPED [1] tests/test_guess.py:40: This is identified as MIME
SKIPPED [1] tests/test_guess.py:46: This is identified as Python
FAILED tests/test_cmdline.py::test_L_opt - assert 1 == 0
================================================================ 1 failed, 3709 passed, 3 skipped in 32.05s ================================================================
```

**Comment by Anteru** [comment] 2021-05-03 16:10
I'm a bit confused - the CI did finish without errors. You have however many more plugins installed than our CI has. Could you please try without all of that and see if it also fails? I can't reproduce it right now, unless something went horribly wrong in the packaging process.

**Comment by Anteru** [comment] 2021-05-03 16:16
I just ran the test suite in a Fedora 35 container with Python 3.9 and it works without issues
```
================================================= test session starts ==================================================
platform linux -- Python 3.9.4, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
Using --randomly-seed=2163680702
rootdir: /pygments, configfile: pytest.ini
plugins: cov-2.11.1, randomly-3.7.0
collected 3713 items
...
3701 passed, 12 skipped in 17.82s
```

**Comment by kloczek** [comment] 2021-05-03 16:20
When I'm usually building rpm packages I have installed only those packages which are listed in BuildRequires😊
However that result was the build on my normal devem env where I have installed Everything™️ 🤪
Sometimes it is good to report result of the pytest in such build env😎

**Comment by Anteru** [comment] 2021-05-03 16:26
Sure, I just don't know what to do about this. Is this caused by your Jinja installation causing some problems? I can't really pinpoint who is at fault here.

**Comment by Anteru** [comment] 2021-05-03 16:56
I'm closing this one for now given this doesn't seem like a Pygments issue.

**Closed by Anteru** 2021-05-03 16:56 UTC

**Comment by kloczek** [comment] 2021-05-03 17:02
If not Pygments issue .. what it could be?🤔

**Comment by Anteru** [comment] 2021-05-03 19:21
A broken Jinja2 filter causing:
```
Error while highlighting:\nDeprecationWarning: \'environmentfilter\' is renamed to \'pass_environment\', the ol...s/jinja2/filters.py
```

This sounds like you have something deprecated in your installation.
