### ISSUE TITLE
pygmentize: command not found

### ISSUE THREAD

**Issue by laraconda** [pygments/pygments#2120] opened 2022-04-26 23:27 UTC
I just installed pygments using `apt-get install python3-pygments` but its not enabled on the command line.

On the official website there's this quote: _You can use Pygments from the shell, provided you installed the pygmentize script_
I wish I could find somewhere *how* to install that script.

I have tried installing this package using `pip3` with no luck either.

OS: Debian 9.3

**Comment by Jean-Abou-Samra** [comment] 2022-04-28 12:35
In principle, `pygmentize` is supposed to be installed with either method. The version in Debian stretch is somewhat outdated though, according to https://packages.debian.org/stretch/python3-pygments it's at 2.2 whereas the latest is 2.12. Regarding `pip3`, are you sure that it didn't skip installing it because it already found it installed on the system? What does `pip3 show pygments` say? Maybe you need to open a new terminal window after installing the package in order to be able to use the command?

**Comment by Jean-Abou-Samra** [comment] 2022-05-29 16:30
Absent further information on how to reproduce this problem (which I have not heard for others), I'm closing this issue. It sounds like a problem with the OS and packaging tools rather than with Pygments itself anyway.

**Closed by Jean-Abou-Samra** 2022-05-29 16:30 UTC
