### ISSUE TITLE
Background in 'Data' Segment is Highlighted in Version 2.11.1 (a change from Version 2.10.0)

### ISSUE THREAD

**Issue by msvedlow** [pygments/pygments#2015] opened 2022-01-02 04:41 UTC
[notes-004-pygments.pptx](https://github.com/pygments/pygments/files/7798559/notes-004-pygments.pptx)
In version 2.11.1 of Pygments, there is a change in how 'data' is displayed.  In version 2.11.1, the 'data' segment is displayed as highlighted text, where the background is highlighted.  In version 2.10.0, the 'data' segment text is colored, but the text is not highlighted in light green.  Please refer to the attached Powerpoint slide.

In the file 'data.py' in the 'lexers' folder, I replaced 'Whitespace' with 'Text' everywhere and commented out 'Whitespace' in the 'import' line so that the 'data' segment is displayed the same as in version 2.10.0.  The replacement is case sensitive and for the full word.

I found that the unhighlighted text in the 'data' segment is easier to read (as in version 2.10.0)

**Comment by amitkummer** [comment] 2022-01-02 18:26
Thanks for reporting this!

I tried to reproduce your output by highlight the problematic json part with both the json and yaml lexers (the lexers that reside in the `data.py` file), but the output seemed fine.

Can you provide us with the full `pygmentize` command you used to highlight this code snippet? It would be very helpful.

**Comment by msvedlow** [comment] 2022-01-03 05:15
I am using HTTPIE with the Pyramid web server on Windows.

The HTTPIE command and response is shown the the ‘command-prompt.png’ image.  The attached ‘code.png’ image contains the Python code used to set the Pyramid route and handle the request.  The attached ‘data.py’ file contains the global change where ‘Whitespace’ is changed to ‘Text’ (case sensitive, full word).

Marty

**Comment by Anteru** [comment] 2022-01-03 07:17
@blu-base Any thoughts? This seems rather weird, but I wonder if that's a state transition ...?

**Comment by blu-base** [comment] 2022-01-03 17:18
@msvedlow, we were looking for this kind of snippet.

```
HTTP/1.1 200 OK
Content-Length: 105
Server: waitress

{
    "action": "GraphDbLoadStaffing",
    "entry_date": "Entry Date",
    "staffing_file_path": "Staffing File Path"
}
```

I don't know yet why there is an issue with the Whitespace. I just changed the lexers, though, not the formatters. Did my contribution trigger some downstream issue?... I am going to look into it now.

**Comment by blu-base** [comment] 2022-01-03 17:46
Ok, so the case is, that the yaml part is detected as a single token with the http lexer. But this is the case for all releases since at least 2.9.0. Continue looking...
```
(pygtest) se@linux:~/projects/pygments> pygmentize -V
Pygments version 2.11.1, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.
(pygtest) se@linux:~/projects/pygments> pygmentize -f tokens -l http httpie.txt 
Token.Keyword.Reserved  'HTTP'
Token.Operator  '/'
Token.Literal.Number    '1.1'
Token.Text      ' '
Token.Literal.Number    '200'
Token.Text      ' '
Token.Name.Exception    'OK'
Token.Text      '\n'
Token.Name.Attribute    'Content-Length'
Token.Text      ''
Token.Operator  ':'
Token.Text      ' '
Token.Literal   '105'
Token.Text      '\n'
Token.Name.Attribute    'Server'
Token.Text      ''
Token.Operator  ':'
Token.Text      ' '
Token.Literal   'waitress'
Token.Text      '\n'
Token.Text      '\n'
Token.Text      '{\n    "action": "GraphDbLoadStaffing",\n    "entry_date": "Entry Date",\n    "staffing_file_path": "Staffing File Path"\n}\n'
```

**Comment by Anteru** [comment] 2022-01-03 19:29
I tried 2.9.0 and 2.10.0 as well and it matches the output @blu-base is getting -- the last bit is a single text token, which means it would not get highlighting. I'm getting the suspicion that this is due to the custom color style here: https://github.com/httpie/httpie/blob/f3b500119c781c16ebb870bb8a2c1c09f6bfdaee/httpie/output/formatters/colors.py because the color must be coming from somewhere, and I think it's either an incorrectly set `background_color` (which blows up with Whitespace) or a missing style definition.

We really need a repro cases which fails with Pygments 2.11 but works with 2.10 to narrow this down.

**Comment by blu-base** [comment] 2022-01-03 19:49
I used the master branches of httpie and pygments and cannot reproduce the issue - see below. I agree, with @Anteru: @msvedlow, please describe in detail how you got your results, report versions, run `pip freeze`.

![image](https://user-images.githubusercontent.com/42077282/147973256-b3417072-0009-4181-ba78-ef9e1e7beb71.png)

**Comment by msvedlow** [comment] 2022-01-03 20:42
The following are the two initial emails that I had responded with containing the information details.  The attachments are included.

I am using HTTPIE with the Pyramid web server on Windows.

The HTTPIE command and response is shown the the ‘command-prompt.png’ image.  The attached ‘code.png’ image contains the Python code used to set the Pyramid route and handle the request.  The attached ‘data.py’ file contains the global change where ‘Whitespace’ is changed to ‘Text’ (case sensitive, full word).

Marty
<img width="960" alt="command-prompt" src="https://user-images.githubusercontent.com/28409951/147978170-4ffc7ba5-5635-4348-925e-7b70b86203f3.png">
<img width="960" alt="code" src="https://user-images.githubusercontent.com/284099
[data.py.txt](https://github.com/pygments/pygments/files/7803932/data.py.txt)
[data_2_11_1_ORIGINAL.py.txt](https://github.com/pygments/pygments/files/7803933/data_2_11_1_ORIGINAL.py.txt)

51/147978185-669f97b4-7977-4f23-8ea0-bbcec46f0b9a.png">

Attached is the original 2.11.1 code for data.py.

Marty

**Comment by blu-base** [comment] 2022-01-03 21:48
> The following are the two initial emails that I had responded with containing the information details. The attachments are included.
>
>  I am using HTTPIE with the Pyramid web server on Windows.

Unfortunately, you assume you included already all the information there is to solve the problem. Maybe i am just not familiar with the three products you mentioned, e.g. i did not know httpie before reading this issue.

As you have noticed, pygments' data.py, containing the json and yaml lexers, has evolved. The `Whitespace` token is a subclass from the `Text` token, explicitly `Text.Whitespace`. Detecting it this way makes the output more specific. 

I fail to find the issue with pygments. Pygment's json lexer will detect the following token for <=2.10 and 2.11, respectively. Both seem fine to me. 
Consider this snippet (including the broken bracket)
```json
    "action": "GraphDbLoadStaffing",
    "entry_date": "Entry Date",
    "staffing_file_path": "Staffing File Path"
}
```


2.11
```
Token.Text.Whitespace   '    '
Token.Name.Tag  '"action"'
Token.Punctuation       ':'
Token.Text.Whitespace   ' '
Token.Literal.String.Double     '"GraphDbLoadStaffing"'
Token.Punctuation       ','
Token.Text.Whitespace   '\n    '
Token.Name.Tag  '"entry_date"'
Token.Punctuation       ':'
Token.Text.Whitespace   ' '
Token.Literal.String.Double     '"Entry Date"'
Token.Punctuation       ','
Token.Text.Whitespace   '\n    '
Token.Name.Tag  '"staffing_file_path"'
Token.Punctuation       ':'
Token.Text.Whitespace   ' '
Token.Literal.String.Double     '"Staffing File Path"'
Token.Text.Whitespace   '\n'
Token.Punctuation       '}'
Token.Text.Whitespace   '\n'
```

2.10
```
Token.Text      '    '
Token.Name.Tag  '"action"'
Token.Punctuation       ':'
Token.Text      ' '
Token.Literal.String.Double     '"GraphDbLoadStaffing"'
Token.Punctuation       ','
Token.Text      '\n    '
Token.Name.Tag  '"entry_date"'
Token.Punctuation       ':'
Token.Text      ' '
Token.Literal.String.Double     '"Entry Date"'
Token.Punctuation       ','
Token.Text      '\n    '
Token.Name.Tag  '"staffing_file_path"'
Token.Punctuation       ':'
Token.Text      ' '
Token.Literal.String.Double     '"Staffing File Path"'
Token.Text      '\n'
Token.Punctuation       '}'
Token.Text      '\n'
```

Maybe focus you attention on httpie and which version you are using.

**Comment by Anteru** [comment] 2022-01-04 08:58
It's especially puzzling as some tokens with the _same_ type get different colors, so even if the whitespace was the culprit, it shouldn't affect them. The only thing I can imagine is that some post-processing pass is failing due to unexpected states, but that's a wild guess. I'm going to close this issue if we don't get a full repro case as we can't resolve it this way.

**Comment by Anteru** [comment] 2022-01-06 10:54
I'm closing this as we can't reproduce. If you can provide more information feel free to reopen.

**Closed by Anteru** 2022-01-06 10:54 UTC
